apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cknugj8x6-nodejs 
  janus-idp.io/tekton: cknugj8x6-nodejs
  backstage.io/kubernetes-id: cknugj8x6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cknugj8x6-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  